# Script for populating the database. You can run it as:
#
#     mix run priv/repo/seeds.exs
#
# Inside the script, you can read and write to any of your
# repositories directly:
#
#     SongRank.Repo.insert!(%SongRank.SomeSchema{})
#
# We recommend using the bang functions (`insert!`, `update!`
# and so on) as they will fail if something goes wrong.
songs = [
  {"I Saw Her Standing There", "please_please_me"},
  {"Misery", "please_please_me"},
  {"Anna (Go To Him)", "please_please_me"},
  {"Chains", "please_please_me"},
  {"Boys", "please_please_me"},
  {"Ask Me Why", "please_please_me"},
  {"Please Please Me", "please_please_me"},
  {"Love Me Do", "please_please_me"},
  {"P.S. I Love You", "please_please_me"},
  {"Baby It's You", "please_please_me"},
  {"Do You Want To Know A Secret", "please_please_me"},
  {"A Taste Of Honey", "please_please_me"},
  {"There's A Place", "please_please_me"},
  {"Twist And Shout", "please_please_me"},
  {"It Won’t Be Long", "with_the_beatles"},
  {"All I’ve Got To Do", "with_the_beatles"},
  {"All My Loving", "with_the_beatles"},
  {"Don’t Bother Me", "with_the_beatles"},
  {"Little Child", "with_the_beatles"},
  {"Till There Was You", "with_the_beatles"},
  {"Please Mister Postman", "with_the_beatles"},
  {"Roll Over Beethoven", "with_the_beatles"},
  {"Hold Me Tight", "with_the_beatles"},
  {"You Really Got A Hold On Me", "with_the_beatles"},
  {"I Wanna Be Your Man", "with_the_beatles"},
  {"Devil In Her Heart", "with_the_beatles"},
  {"Not A Second Time", "with_the_beatles"},
  {"Money (That’s What I Want)", "with_the_beatles"},
  {"No Reply", "beatles_for_sale"},
  {"I'm A Loser", "beatles_for_sale"},
  {"Baby's In Black", "beatles_for_sale"},
  {"Rock And Roll Music", "beatles_for_sale"},
  {"I'll Follow The Sun", "beatles_for_sale"},
  {"Mr. Moonlight", "beatles_for_sale"},
  {"Medley: Kansas City / Hey, Hey, Hey, Hey", "beatles_for_sale"},
  {"Eight Days A Week", "beatles_for_sale"},
  {"Words Of Love", "beatles_for_sale"},
  {"Honey Don't", "beatles_for_sale"},
  {"Every Little Thing", "beatles_for_sale"},
  {"I Don't Want To Spoil The Party", "beatles_for_sale"},
  {"What You're Doing", "beatles_for_sale"},
  {"Everybody's Trying To Be My Baby", "beatles_for_sale"},
  {"A Hard Day's Night", "hard_days_night"},
  {"I Should Have Known Better", "hard_days_night"},
  {"If I Fell", "hard_days_night"},
  {"I'm Happy Just to Dance With You", "hard_days_night"},
  {"And I Love Her", "hard_days_night"},
  {"Tell Me Why", "hard_days_night"},
  {"Can't Buy Me Love", "hard_days_night"},
  {"Any Time at All", "hard_days_night"},
  {"I'll Cry Instead", "hard_days_night"},
  {"Things We Said Today", "hard_days_night"},
  {"When I Get Home", "hard_days_night"},
  {"You Can't Do That", "hard_days_night"},
  {"I'll Be Back", "hard_days_night"},
  {"Help!", "help"},
  {"The Night Before", "help"},
  {"You've Got To Hide Your Love Away", "help"},
  {"I Need You", "help"},
  {"Another Girl", "help"},
  {"You're Going To Lose That Girl", "help"},
  {"Ticket To Ride", "help"},
  {"Act Naturally", "help"},
  {"It's Only Love", "help"},
  {"You Like Me Too Much", "help"},
  {"Tell Me What You See", "help"},
  {"I've Just Seen A Face", "help"},
  {"Yesterday", "help"},
  {"Dizzy Miss Lizzy", "help"},
  {"Drive My Car", "rubber_soul"},
  {"Norwegian Wood (This Bird Has Flown)", "rubber_soul"},
  {"You Won't See Me", "rubber_soul"},
  {"Nowhere Man", "rubber_soul"},
  {"Think For Yourself", "rubber_soul"},
  {"The Word", "rubber_soul"},
  {"Michelle", "rubber_soul"},
  {"What Goes On", "rubber_soul"},
  {"Girl", "rubber_soul"},
  {"I'm Looking Through You", "rubber_soul"},
  {"In My Life", "rubber_soul"},
  {"Wait", "rubber_soul"},
  {"If I Needed Someone", "rubber_soul"},
  {"Run For Your Life", "rubber_soul"},
  {"Taxman", "revolver"},
  {"Eleanor Rigby", "revolver"},
  {"I'm Only Sleeping", "revolver"},
  {"Love You To", "revolver"},
  {"Here, There And Everywhere", "revolver"},
  {"Yellow Submarine", "revolver"},
  {"She Said, She Said", "revolver"},
  {"Good Day Sunshine", "revolver"},
  {"And Your Bird Can Sing", "revolver"},
  {"For No One", "revolver"},
  {"Doctor Robert", "revolver"},
  {"I Want To Tell You", "revolver"},
  {"Got To Get You Into My Life", "revolver"},
  {"Tomorrow Never Knows", "revolver"},
  {"Sgt. Pepper's Lonely Hearts Club Band", "sgt_peppers_lonely_hearts_club_band"},
  {"With A Little Help From My Friends", "sgt_peppers_lonely_hearts_club_band"},
  {"Lucy In The Sky With Diamonds", "sgt_peppers_lonely_hearts_club_band"},
  {"Getting Better", "sgt_peppers_lonely_hearts_club_band"},
  {"Fixing A Hole", "sgt_peppers_lonely_hearts_club_band"},
  {"She's Leaving Home", "sgt_peppers_lonely_hearts_club_band"},
  {"Being For The Benefit Of Mr. Kite!", "sgt_peppers_lonely_hearts_club_band"},
  {"Within You Without You", "sgt_peppers_lonely_hearts_club_band"},
  {"When I'm Sixty Four", "sgt_peppers_lonely_hearts_club_band"},
  {"Lovely Rita", "sgt_peppers_lonely_hearts_club_band"},
  {"Good Morning, Good Morning", "sgt_peppers_lonely_hearts_club_band"},
  {"Sgt. Pepper's Lonely Hearts Club Band (Reprise)", "sgt_peppers_lonely_hearts_club_band"},
  {"A Day In The Life", "sgt_peppers_lonely_hearts_club_band"},
  {"Magical Mystery Tour", "magical_mystery_tour"},
  {"The Fool On The Hill", "magical_mystery_tour"},
  {"Flying", "magical_mystery_tour"},
  {"Blue Jay Way", "magical_mystery_tour"},
  {"Your Mother Should Know", "magical_mystery_tour"},
  {"I Am The Walrus", "magical_mystery_tour"},
  {"Hello, Goodbye", "magical_mystery_tour"},
  {"Strawberry Fields Forever", "magical_mystery_tour"},
  {"Penny Lane", "magical_mystery_tour"},
  {"Baby, You're A Rich Man", "magical_mystery_tour"},
  {"All You Need Is Love", "magical_mystery_tour"},
  {"Back In The U.S.S.R", "the_beatles_the_white_album"},
  {"Dear Prudence", "the_beatles_the_white_album"},
  {"Glass Onion", "the_beatles_the_white_album"},
  {"Ob-La-Di, Ob-La-Da", "the_beatles_the_white_album"},
  {"Wild Honey Pie", "the_beatles_the_white_album"},
  {"The Continuing Story Of Bungalow Bill", "the_beatles_the_white_album"},
  {"While My Guitar Gently Weeps", "the_beatles_the_white_album"},
  {"Happiness Is A Warm Gun", "the_beatles_the_white_album"},
  {"Martha My Dear", "the_beatles_the_white_album"},
  {"I'm So Tired", "the_beatles_the_white_album"},
  {"Blackbird", "the_beatles_the_white_album"},
  {"Piggies", "the_beatles_the_white_album"},
  {"Rocky Raccoon", "the_beatles_the_white_album"},
  {"Don't Pass Me By", "the_beatles_the_white_album"},
  {"Why Don't We Do It In The Road?", "the_beatles_the_white_album"},
  {"I Will", "the_beatles_the_white_album"},
  {"Julia", "the_beatles_the_white_album"},
  {"Birthday", "the_beatles_the_white_album"},
  {"Yer Blues", "the_beatles_the_white_album"},
  {"Mother Nature's Son", "the_beatles_the_white_album"},
  {"Everybody's Got Something To Hide Except Me And My Monkey", "the_beatles_the_white_album"},
  {"Sexy Sadie", "the_beatles_the_white_album"},
  {"Helter Skelter", "the_beatles_the_white_album"},
  {"Long, Long, Long", "the_beatles_the_white_album"},
  {"Revolution 1", "the_beatles_the_white_album"},
  {"Honey Pie", "the_beatles_the_white_album"},
  {"Savoy Truffle", "the_beatles_the_white_album"},
  {"Cry Baby Cry", "the_beatles_the_white_album"},
  {"Revolution 9", "the_beatles_the_white_album"},
  {"Good Night", "the_beatles_the_white_album"},
  {"Yellow Submarine", "yellow_submarine"},
  {"Only A Northern Song", "yellow_submarine"},
  {"All Together Now", "yellow_submarine"},
  {"Hey Bulldog", "yellow_submarine"},
  {"It's All Too Much", "yellow_submarine"},
  {"All You Need Is Love", "yellow_submarine"},
  {"Pepperland", "yellow_submarine"},
  {"Medley: Sea Of Time & Sea Of Holes", "yellow_submarine"},
  {"Sea Of Monsters", "yellow_submarine"},
  {"March Of The Meanies", "yellow_submarine"},
  {"Pepperland Laid Waste", "yellow_submarine"},
  {"Yellow Submarine In Pepperland", "yellow_submarine"},
  {"Come Together", "abbey_road"},
  {"Something", "abbey_road"},
  {"Maxwell's Silver Hammer", "abbey_road"},
  {"Oh! Darling", "abbey_road"},
  {"Octopus's Garden", "abbey_road"},
  {"I Want You (She's So Heavy)", "abbey_road"},
  {"Here Comes The Sun", "abbey_road"},
  {"Because", "abbey_road"},
  {"You Never Give Me Your Money", "abbey_road"},
  {"Sun King", "abbey_road"},
  {"Mean Mr. Mustard", "abbey_road"},
  {"Polythene Pam", "abbey_road"},
  {"She Came In Through The Bathroom Window", "abbey_road"},
  {"Golden Slumbers", "abbey_road"},
  {"Carry That Weight", "abbey_road"},
  {"The End", "abbey_road"},
  {"Her Majesty", "abbey_road"},
  {"Two Of Us", "let_it_be"},
  {"Dig A Pony", "let_it_be"},
  {"Across The Universe", "let_it_be"},
  {"I Me Mine", "let_it_be"},
  {"Dig It", "let_it_be"},
  {"Let It Be", "let_it_be"},
  {"Maggie Mae", "let_it_be"},
  {"I've Got A Feeling", "let_it_be"},
  {"One After 909", "let_it_be"},
  {"The Long And Winding Road", "let_it_be"},
  {"For You Blue", "let_it_be"},
  {"Get Bac", "let_it_be"}
]

Enum.each(songs, fn s ->
  song = %SongRank.Song{title: elem(s, 0), image: elem(s, 1)}
  SongRank.Repo.insert(song)
end)
